models/contact.py
from utils.db import db

class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(100))
    email = db.Column(db.String(100))
    message = db.Column(db.String(500))
    response = db.Column(db.String(500))

    def __init__(self, fullname, email, message, response):
        self.fullname = fullname
        self.email = email
        self.message = message
        self.response = response

app.py
from flask import Flask
from routes.contacts import contacts
from flask_sqlalchemy import SQLAlchemy
from config import DATABASE_CONNECTION_URI

app = Flask(__name__)

app.secret_key = b'_5#y2L"F4Q8z\n\xec]/' #usado por flash

#app.config["SQLALCHEMY_DATABASE_URI"] = 'mysql://root:admin@localhost/peliflixDB'
app.config["SQLALCHEMY_DATABASE_URI"] =  DATABASE_CONNECTION_URI
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

SQLAlchemy(app)

app.register_blueprint(contacts)

routes/contacts.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.contact import Contact
from utils.db import db

contacts = Blueprint('contacts', __name__)

@contacts.route("/")
def home():
    return render_template('index.html')

@contacts.route("/new", methods=['POST'])
def add():
    fullname = request.form['contact-name']
    email = request.form['contact-email']
    message = request.form['contact-message']
    response = ''    
    new_contact = Contact(fullname, email, message, response)
    db.session.add(new_contact)
    db.session.commit()

    flash("Hemos recibido su mensaje")
    return redirect('/')

@contacts.route("/manage-contacts")
def manage():
    contacts = Contact.query.all();
    return render_template('manage-contacts.html', contacts=contacts)

@contacts.route("/delete/<id>")
def delete(id):
    contact = Contact.query.get(id)
    db.session.delete(contact)
    db.session.commit()
    return redirect(url_for('contacts.manage'))

@contacts.route("/update/<id>", methods=['POST', 'GET'])
def update(id):
    contact = Contact.query.get(id)
    if request.method == "POST":
        contact = Contact.query.get(id)
        responseText = request.form['contact-response']
        contact.response = responseText

        db.session.commit()
        return redirect(url_for('contacts.manage'))
    
    return render_template('update-contact.html', contact=contact)

templates/index.html
<!DOCTYPE html>
<html lang="es">

{% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for messages in messages %}
      {{ message }}
    {% endfor %}
  {% endif %}
{% endwith %}

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>PeliFlix</title>
  <link rel="preconnect" href="https://fonts.gstatic.com" />

  <!-- fuentes Montserrat-->
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700&display=swap" rel="stylesheet" />
  <!-- fuentes Bebas Neue y Open Sans-->
  <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Open+Sans:wght@400;600&display=swap"
    rel="stylesheet">

  <!-- iconos -->
  <script src="https://kit.fontawesome.com/2c36e9b7b1.js" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.1/normalize.min.css" />
  <link rel="stylesheet" href="/static/css/main.css" />
  <link rel="stylesheet" href="/static/css/navbar.css" />
  <link rel="stylesheet" href="/static/css/home.css" />
  <link rel="stylesheet" href="/static/css/contact.css" />
  <link rel="stylesheet" href="/static/css/carousel.css" />
  <link rel="stylesheet" href="/static/css/subscribe.css" />
  <link rel="stylesheet" href="/static/css/footer.css">
  <link rel="stylesheet" href="/static/css/videos.css">
  <link rel="stylesheet" href="/static/css/responsive.css">



</head>

<div id="myNav" class="overlay">

  <!-- Button to close the overlay navigation -->
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>

  <!-- Overlay content -->
  <div class="overlay-content" id="overlay-content"></div>

  <a href="javascript:void(0)" class="arrow left-arrow" id="left-arrow">&#8656;</a>

  <a href="javascript:void(0)" class="arrow right-arrow" id="right-arrow">&#8658;</a>

</div>


<body>
  <header class="topheader">
    <nav class="topnav">
      <a href="#" class="logo">
        <img height="50" width="50" src="/static/img/logo2.png" alt="imagen logo" />
        <div class="logotype">
          PELIFLIX
        </div>
      </a>
      <button class="open-menu" aria-label="Abrir menú">
        <img src="/static/img/icons8-menu.svg" alt="abrir menú" />
      </button>
      <ul class="menu">
        <li>
          <button class="close-menu" aria-label="Cerrar menú">
            <img src="/static/img/icons8-close-32.svg" alt="cerrar menú" />
          </button>
        </li>
        <li><a href="#home" class="selected">Inicio</a></li>
        <li><a href="#popular">Populares</a></li>
        <li><a href="#trending">Tendencia</a></li>
        <li><a href="#acclaimed">Aclamadas</a></li>
        <li><a href="#contact">Contacto</a></li>
        <li><a href="#subscribe">Suscripción</a></li>
      </ul>
    </nav>
  </header>

  <!-- Home Section -->
  <div class="horizontal-padding vertical-padding">
    <section class="home" id="home">
      <div class="main-movie">
        <div class="container">
          <h2 class="volanta"> Lo mas visto hoy</h2>
          <h3 class="title"></h3>
          <p class="description"></p>
          <button role="button" class="play-button" id="main-movie-play"><i
              class="fas fa-play"></i>Reproducir</button>
        </div>
      </div>
    </section>
  </div>

  <!-- Popular Section -->
  <div class="horizontal-padding vertical-padding">
    <section class="section" id="popular">
      <h2 class="section-category">Las mas populares...</h2>
      <button class="pre-btn"><img src="/static/img/double-right-arrows.png" alt=""></button>
      <button class="nxt-btn"><img src="/static/img/double-right-arrows.png" alt=""></button>
      <div class="carousel-container" id="popular-container">

      </div>

    </section>
  </div>

  <!-- Trending Section -->
  <div class="horizontal-padding vertical-padding">
    <section class="section" id="trending">
      <h2 class="section-category">Son tendencia en la última semana...</h2>
      <button class="pre-btn"><img src="/static/img/double-right-arrows.png" alt=""></button>
      <button class="nxt-btn"><img src="/static/img/double-right-arrows.png" alt=""></button>
      <div class="carousel-container" id="trending-container">

      </div>

    </section>
  </div>

  <!-- Acclaimed Section -->
  <div class="horizontal-padding vertical-padding">
    <section class="section" id="acclaimed">
      <h2 class="section-category">Aclamadas por la crítica...</h2>
      <button class="pre-btn"><img src="/static/img/double-right-arrows.png" alt=""></button>
      <button class="nxt-btn"><img src="/static/img/double-right-arrows.png" alt=""></button>
      <div class="carousel-container" id="acclaimed-container">

      </div>
    </section>
  </div>

  <!-- Contact Section -->
  <div class="horizontal-padding vertical-padding">
    <section class="contact" id="contact">
      <h2 class="section-category">Contacto</h2>
      <div class="contact-details">
        <div class="contact-details-group">
          <p class="contact-label">Dirección:</p>
          <p class="contact-text">Ciudad Autónoma de Buenoas Aires, Argentina</p>
        </div>
        <div class="contact-details-group">
          <p class="contact-label">Email:</p>
          <p class="contact-text">info@peliflix.com.ar</p>
        </div>
        <div class="contact-details-group">
          <p class="contact-text">
            Deje su mensaje y con gusto le responderemos
          </p>
        </div>
      </div>
      <form class="contact-form" id="contact-form" name="contact" action="/new" method="POST">
        <div class="form-control">
          <label for="contact-name">Nombre</label>
          <input type="text" name="contact-name" id="contact-name" placeholder="Ingrese su nombre" />
          <small>Error Message</small>
        </div>
        <div class="form-control">
          <label for="contact-email">Email</label>
          <input name="contact-email" id="contact-email" placeholder="Ingrese su email" />
          <small>Error Message</small>
        </div>
        <div class="form-control">
          <label for="contact-message">Mensaje</label>
          <textarea name="contact-message" id="contact-message" placeholder="Ingrese el mensaje" rows="6"></textarea>
          <small>Error Message</small>
        </div>
        <button type="submit" class="form-submit" id="contact-submit">Enviar</button>
        <div class="submit-message">
          <div class="success" id="contact-submit-success">Hemos recibido tu mensaje! pronto te responderemos!</div>
          <div class="error" id="contact-submit-error">Formulario no enviado</div>
        </div>
      </form>
    </section>
  </div>

  <!-- Subscribe Section -->
  <div class="horizontal-padding vertical-padding">
    <section class="subscribe-area" id="subscribe">
     <!--  <div class="container"> -->
        <div class="subscribe">
          <h4>Todas las novedades</h4>
          <p>Mantenete al tanto de las últimas noticias del mundo del cine.</p>
          <form class="subscribe-form" id="subscribe-form">
            <div class="form-control">
              <input name="subscribe-email" id="subscribe-email" type="text" placeholder="Ingrese su email" />
              <small>Error Message</small>
              <!-- <input type="submit" value="Suscribite"> -->
              <button type="submit" class="form-submit" id="subscribe-submit">Suscribirse</button>
            </div>
            <div class="submit-message">
              <div class="success" id="subscribe-submit-success">Felicitaciones! ya estás suscripto!</div>
              <div class="error" id="subscribe-submit-error">Formulario no enviado</div>
            </div>
          </form>
        </div>
      <!-- </div> -->
    </section>
  </div>

  <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="footer-col">
          <h4>Empresa</h4>
          <ul>
            <li><a href="#">Sobre nosotros</a></li>
            <li><a href="#">Nuestros servicios</a></li>
            <li><a href="#">Política de privacidad</a></li>
            <li><a href="#">Versión Premium</a></li>
          </ul>
        </div>
        <div class="footer-col">
          <h4>Ayuda</h4>
          <ul>
            <li><a href="#">Preguntas frecuentes</a></li>
            <li><a href="#">Estado de contratación</a></li>
            <li><a href="#">Cancelación de Suscripción</a></li>
          </ul>
        </div>
        <div class="footer-col">
          <h4>Seguinos</h4>
          <div class="social-links">
            <a href="#"><i class="fab fa-facebook-f"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
          </div>
        </div>
      </div>
    </div>
  </footer>


  <!-- javascript code-->
  <script defer src="/static/js/main.js"></script>
  <script defer src="/static/js/navbar.js"></script>
  <script defer src="/static/js/videos.js"></script>
  <script defer src="/static/js/home.js"></script>
  <script defer src="/static/js/popular.js"></script>
  <script defer src="/static/js/trending.js"></script>
  <script defer src="/static/js/acclaimed.js"></script>
  <script defer src="/static/js/contact.js"></script>
  <script defer src="/static/js/subscribe.js"></script>
</body>

</html>

templates/manage-contacts.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>

  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

  <title>Peliflix Admin</title>

</head>

<body>
  <h1 class="bd-title">Gestión de respuestas a contactos</h1>
  <br>
  <table class="table table-dark table-striped table-hover">
    <thead >
      <tr  class="text-warning">
        <th scope="col">#</th>
        <th scope="col">Nombre</th>
        <th scope="col">Correo</th>
        <th scope="col">Mensaje Usuario</th>
        <th scope="col">Respuesta</th>
        <th scope="col">Acción</th>

      </tr>
    </thead>
    <tbody>
      {% for contact in contacts %}
      <tr d-flex>
        <th scope="row">{{contact.id}}</th>
        <td>{{contact.fullname}}</td>
        <td>{{contact.email}}</td>
        <td>{{contact.message}}</td>
        <td>{{contact.response}}</td>
        <td>            
          <a href="{{ url_for('contacts.update', id=contact.id) }}" class="btn btn-primary btn-sm rounded-0">Edit</a>
          <a href="{{ url_for('contacts.delete', id=contact.id) }}" class="btn btn-danger btn-sm rounded-0">Delete</a>
        </td>
      </tr>
      {% endfor %}

    </tbody>
  </table>



  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    crossorigin="anonymous"></script>
</body>

</html>

templates/update-contact.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="/static/css/main.css" />
  <link rel="stylesheet" href="/static/css/contact.css" />

  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

  <title>Peliflix Admin</title>

</head>

<body>


  <div class="horizontal-padding vertical-padding">
    <section class="contact" id="contact">
      <h2 class="section-category text-primary" >Editar respuesta a Contacto de Usuarios</h2>
      <div class="contact-details">
        <div class="contact-details-group">
          <p class="contact-label text-warning">Nombre:</p>
          <p class="contact-text">{{contact.fullname}}</p>
        </div>
        <div class="contact-details-group">
          <p class="contact-label text-warning">Email:</p>
          <p class="contact-text">{{contact.email}}</p>
        </div>
        <div class="contact-details-group">
          <p class="contact-label text-warning">Mensaje dejado por el usuario:</p>
          <p class="contact-text">
            {{contact.message}}
          </p>
        </div>
      </div>
      <form class="contact-form" id="contact-form" name="contact" action="/update/{{contact.id}}" method="POST">
       
          <textarea name="contact-response" id="contact-response" placeholder="Ingrese la respuesta" cols="100" rows="5">{{contact.response}}</textarea>
       
        <button type="submit" class="form-submit" id="contact-submit">Guardar</button>
      </form>
      </section>
  </div>


  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    crossorigin="anonymous"></script>
</body>

</html>